### ISSUE TITLE
Char with Scroll of Restitance in Inv  not loading

### ISSUE THREAD

**Issue by marrvin2** [dschu012/d2s-editor#1]
Hi Danny,

I am using your web char editor to modify d2r saved chars.
The editor will not load my char that has the "Scroll of Resistance"  (Act 5 Anja resuce reward)  in the invetory.
After using the scroll  I could again load my char.

Find the char with the scroll  included in the attached ZIP File ;)
Happy Debugging!  

[Zaubermaus.zip](https://github.com/dschu012/d2s-editor/files/6548973/Zaubermaus.zip)

**Comment by dschu012** [comment]
Think I fixed it.
