### ISSUE TITLE
Base Item sockets number not correct

### ISSUE THREAD

**Issue by thpnick688** [dschu012/d2s-editor#102]
Hello. I find that if you want to load a base item for rune word the socket number is set to 3 as max. 
For example, I want to load a Great Poleaxe with 4 sockets to craft runeword Infinity. The final Great Poleaxe I got after loading only has 3 socktes. This issue also happens with other Polearms items like Scythe

**Comment by spg-stany** [comment]
up item-level > 41

**Comment by thpnick688** [comment]
Thank you very much for the tips.

**Comment by spg-stany** [comment]
#101 fixed
