### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by Chuckskyline** [dschu012/d2s-editor#107]
Every time I try to access https://d2s.dschu012.dev/ its down. It worked a few times but throughout the weekend it would randomly stop working and just not access the website at all. 

Trying to use https://dschu012.github.io/d2s/editor/ this works but none of the items display and it doesn't show all of the items. For example on the https://d2s.dschu012.dev/ you can upload "normal" weapons or exceptional or elite standard weapons, on the github.io one you can't

Is there an alternative? I really love messing and tinkering around in d2 and sort of brought me back to the game. 

Thanks!

**Comment by dschu012** [comment]
Server was down. Up again now.
