### ISSUE TITLE
SaveD2R doesn't work

### ISSUE THREAD

**Issue by rahjuu** [dschu012/d2s-editor#111]
I uploaded the d2s file of an existing character, and made some changes to the character stats and items. So far everthing works fine. Then I click SaveD2R, nothing happened. To my understanding, a d2s file will be downloaded after I click SaveD2R button.

Could you help to look into this?

BTW, if I create a new character, d2s file will be downloaded after I click SaveD2R.

**Comment by shpark89** [comment]
I can download the file but when I replace the original .d2s file, the file seems unchanged

**Comment by rahjuu** [comment]
The file can be downloaded after disabling the VPN
