### ISSUE TITLE
Respec option is lost if a character is downloaded from the site

### ISSUE THREAD

**Issue by georgit** [dschu012/d2s-editor#113]
This might be easier to explain in steps:
1. If you take a character and beat the den of evil, you get a respec from Akara
2. You take that character and upload it to the editor
3. You download it back from the editor and put it in your save folder
4. The respec option is now gone.

It's not that bad, since if you're using the editor you can obvs give yourself a token of absolution, so I'm really not complaining but should report it anyway. Editor is great and I love it. Also, Larzuk-ing, Anya-ing, and Charsi-ing still work after the steps above, it's really just Akara that seems broken.

**Comment by Raizuto** [comment]
or you simply add "-enablerespec" to the special command line to the game options in the launcher - this allows for unlimited respecs on the fly.
