### ISSUE TITLE
Server unstable

### ISSUE THREAD

**Issue by moonlight618** [dschu012/d2s-editor#116]
Hi it appears the server is down again.
Every so often it would show as 504 bad gateway timeout. 
Is there any way to solve the problem for good, or is there any alt sites other than https://dschu012.github.io/d2s/editor/?

Many thanks.

**Comment by dschu012** [comment]
Back up. I don't plan on changing the hosting situation anytime soon, but nothing is stopping you (or anyone else from) hosting it elsewhere in a more stable environment.

**Comment by moonlight618** [comment]
> Back up. I don't plan on changing the hosting situation anytime soon, but nothing is stopping you (or anyone else from) hosting it elsewhere in a more stable environment.

Sorry I'm not a tech person.
Can you teach me how exactly do I host it?
Thanks.
