### ISSUE TITLE
Editor is broken

### ISSUE THREAD

**Issue by spg-stany** [dschu012/d2s-editor#129]
problem 1 
stats-editor not rendering
after load 1 item any loads other items ends with error and stats-editor not rendering
possible reason in new constants @dschu012 
https://github.com/dschu012/d2s-editor/commit/a55c1acbd199fda31497399f37a9a410c6002161#diff-dba22eaf8b7296b392a655e8f75784f8a47a714fcd1906824923f857a59a59aa

steps to reproduce
create new amason
load item thunderstrore
VM4316:48 Uncaught (in promise) TypeError: Cannot read properties of null (reading 's')
    at eval (eval at compileToFunction (vue@3.0.4:13517:24), <anonymous>:48:78)
    at renderList (vue@3.0.4:8020:24)

problem 2
d2s saves not loading
last version
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at d2s.bundle.min.js:1:42402
    at String.replace (<anonymous>)
    at d2s.bundle.min.js:1:42352
Item.js:143 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at Item.js:143:64
    at Proxy.map (<anonymous>)
    at Proxy.itemName (Item.js:143:43)
/data/global/items/undefined.dc6:1          Failed to load resource: the server responded with a status of 404 (Not Found)

other version
Uncaught (in promise) Error: Save Bits is undefined for stat: 30:nextexp at position 11175
    at v (d2s.bundle.min.js:1:65730)
    at d2s.bundle.min.js:1:60567
    at d2s.bundle.min.js:1:53863
    at Object.next (d2s.bundle.min.js:1:53968)
or
Uncaught (in promise) Error: Invalid Stat Id: 458 at position 15739
    at v (d2s.bundle.min.js:1:65320)
    at d2s.bundle.min.js:1:60403
    at d2s.bundle.min.js:1:53863
    at Object.next (d2s.bundle.min.js:1:53968)
    at d2s.bundle.min.js:1:52880

**Comment by dschu012** [comment]
You might need to clear your cache and do a fresh reload? I just loaded up 4 or 5 items in a row w/o issue.

![image](https://user-images.githubusercontent.com/1458109/194119294-91d13f2c-c3ae-4b3a-9f8d-e10a24d4574f.png)

**Comment by dschu012** [comment]
But just from looking at that pic. Seems a lot of the strings got broken in this update....

**Comment by RBReyns** [comment]
Yes, I'm running into the same issue. I can't load previous .d2s files, can only load items to the inventory and not on the equipped section. Also if I right click an item to delete the dialogue box never goes away and won't delete or copy any items

**Comment by dschu012** [comment]
think a lot of those issues should be fixed now. I was trying to fix the new sunder charms, turned out to be a pretty big change because the new stats added into the game because of them.

**Comment by spg-stany** [comment]
thank you @dschu012 
and merge my fix plz https://github.com/dschu012/d2s-editor/pull/130
