### ISSUE TITLE
Errors thrown when loading char's .d2s file

### ISSUE THREAD

**Issue by Pasty44** [dschu012/d2s-editor#133]
With latest change I'm getting an error when trying to open one of my chars d2s files in the editor. The char had been edited before, though mostly just adding/tweaking some stats. Nothing crazy. I attached a zip with the .d2s in it. Errors:

```
Uncaught (in promise) Error: No handler for descVal: undefined
...
[d2s.bundle.min.js:1:43217](https://github.com/dschu012/d2s/releases/latest/download/d2s.bundle.min.js)
```

```
Uncaught (in promise) TypeError: e.type_name is undefined
    runes https://d2s.dschu012.dev/js/components/inventory/Item.js:143
    ...
[Item.js:143:52](https://d2s.dschu012.dev/js/components/inventory/Item.js)
```
[Nikka.zip](https://github.com/dschu012/d2s-editor/files/9732454/Nikka.zip)

**Comment by dschu012** [comment]
should open now. some of the property descriptions are buggy still.
