### ISSUE TITLE
I have some requests to you.

### ISSUE THREAD

**Issue by AROKP** [dschu012/d2s-editor#143]
Hello.

I'm a Korean resurected user. I'm using your editor with great satisfaction. Thank you for your service.

I tried make 'Guillaume's Face Winged Helm and unique wands with your editor, but I couldn't because they weren't on the list.

So I ask you to include them in the list so that I can make them with an editor.

please. ㅠ

Please understand if my English is not good enough and my writing makes you feel bad. As mentioned earlier, I am Korean, so it is impossible to speak English perfectly, politely, and kindly.

thank you.

**Comment by dschu012** [comment]
![image](https://user-images.githubusercontent.com/1458109/205289836-3d3ec061-e1e2-444d-9d8f-61b80b7823cf.png)

gface should be there. you need to search by the name of the set. idk what unique wands you are talking about? suicide branch? someone would have to provide a save w/ the item for me to do that.
