### ISSUE TITLE
Charm poison editor doesn't seem intuitive (or at least lets us set values that make sense)

### ISSUE THREAD

**Issue by twig** [dschu012/d2s-editor#164]
Tried to combine several poison charms with varying damage/duration values, entered 95 for poison damage.

Came out as "6 damage over 3 sec", so no idea what I should have expected to happen.

**Comment by twig** [comment]
ok looks like the values and times are flipped after making changes

|        | In Game |      |   | In Editor |      |
|--------|---------|------|---|-----------|------|
|        | Damage  | Time |   | Damage    | Time |
| Item 1 | 6       | 3    |   | 21        | 6    |
| Item 2 | 15      | 4    |   | 39        | 15   |
| Item 3 | 10      | 3    |   | 35        | 10   |

**Comment by twig** [comment]
https://www.theamazonbasin.com/wiki/index.php/Poison_Damage

> Poison damage is displayed as the total damage applied over its length, but it's calculated by applying its 1/256 damage rate for a specified number of frames: a Toxic [Small Charm](https://www.theamazonbasin.com/wiki/index.php?title=Small_Charm) applies poison damage at a rate of 205/256 for 125 frames, which is displayed as 100 Poison Damage Over 5 Seconds (125 * 205/256 over 125/25).

**Comment by retro-pc** [comment]
@twig hi
test it now plz
make screens

**Comment by twig** [comment]
Sorry I don't have the game installed anymore 😅
