### ISSUE TITLE
Changing mundane item to magic or rare makes us unable to save

### ISSUE THREAD

**Issue by sittingsparrow** [dschu012/d2s-editor#174]
Recreating rare items from i.e. an amulet and changing the item type from Unique to Rare or Normal to Rare bugs out the save button.

Note 1: I read through the open issues and I believe this isn't a duplicate.
Note 2: Great tool, thanks for making it, is there a way to add my own templates/missing items?

**Comment by spg-stany** [comment]
@sittingsparrow 
pull request with file /src/d2/ItemPack.js is way to add my own templates/missing items

**Comment by spg-stany** [comment]
@sittingsparrow hi
you can say me missing items list here

**Comment by retro-pc** [comment]
#197
