### ISSUE TITLE
The properties of the 'second' item in inventory are copied to the second item.

### ISSUE THREAD

**Issue by BramVos** [dschu012/d2s-editor#18]
The properties of the 'second' item in inventory are copied to the second item. I had a tome of Town Portal next to a Tome of Identify next to each other. After saving my Tome of Town Portal still was blue but it became a Tome of Identify.

**Comment by DAT-SQUAZZ** [comment]
I had this happen with no tome of identify in inventory. Seems to be a problem with tomes of town portal. It became unusable and named Tome of Identify.
