### ISSUE TITLE
bug report and suggestion

### ISSUE THREAD

**Issue by hm52091** [dschu012/d2s-editor#193]
Hello, 

First of all, I'm using the editor well. Thanks.

and I'm gonna give you a bug report and a suggestion.

1. socket genaration bug

The editor appears to have created a socket, but not in the game.

Tested with a few weapons including Champion Axe.

2. suggestion

I wish I could choose gems from item load

Thank you.

**Comment by spg-stany** [comment]
#194

**Comment by retro-pc** [comment]
#197
