### ISSUE TITLE
items - add gems?

### ISSUE THREAD

**Issue by crashinz** [dschu012/d2s-editor#2]
hi, could you add the ability to put gems onto the character through the items selection choice?

note: i tried to convert a brand new character to d2, add in gems with hero editor, then convert it back but i get something about bad quest data (didnt do any other changes)

**Comment by dschu012** [comment]
I'll try to add them later when I get a chance, but a workaround is:

1) Create new char.
2) Click scroll of town portal or identity
3) Change item type to "Perfect Topaz" (or whatever gem you want).
4) Open up the save you are editing in another browser window.
5) Drag the gem from the first browser window to where you want in on your save.
6) Save D2R.

![image](https://user-images.githubusercontent.com/1458109/120381431-69543d00-c2f0-11eb-87f8-98f91d811a6f.png)
