### ISSUE TITLE
Bug Report: IK set not adding partial set bonuses

### ISSUE THREAD

**Issue by nickdecastro** [dschu012/d2s-editor#211]
The Immortal King set does not have the  partial set bonuses when wearing the set. I.E. elemental damage on the weapon.
The full set bonus appears; just not the partials.
There is a workaround. The add stats option allows you to add them manually.

Thanks again!

**Comment by retro-pc** [comment]
you have partial set bonuses in game?

**Comment by nickdecastro** [comment]
My barb is wearing the full set but the partial set bonuses are not there
by default but I can "add stat" to put them on myself.
The green text in the following screenshot.

[image: image.png]

Thank you,
Nick

**Comment by retro-pc** [comment]
i have all bonuses 
<img width="285" alt="Screenshot 2024-04-03 224135" src="https://github.com/dschu012/d2s-editor/assets/16412355/440dc91d-3ead-45d3-8c7f-961a3cb9b4cd">
<img width="350" alt="Screenshot 2024-04-01 184442" src="https://github.com/dschu012/d2s-editor/assets/16412355/12698f26-78a6-4c7f-a155-3c89781ace37">

**Comment by nickdecastro** [comment]
Let's see an in-game screenshot.
Thank you,
Nick

**Comment by retro-pc** [comment]
bonuses calculated in game
