### ISSUE TITLE
Some pre-made templates not save-able in LOD version

### ISSUE THREAD

**Issue by AudriusButkevicius** [dschu012/d2s-editor#217]
Tried a few different sorc templates
![image](https://github.com/dschu012/d2s-editor/assets/1144861/0d959dec-8cd4-4e80-91c0-30a9499e7729)

Separate bug:
hdin template doesn't work either, "cannot enter game, bad hireable", in LOD.

**Comment by retro-pc** [comment]
needs remove sunder charm from inventory
