### ISSUE TITLE
The % Enhanced Damage stat is bugged.

### ISSUE THREAD

**Issue by Argonil** [dschu012/d2s-editor#22]
Modifying the % Enhanced Damage stat doesn't work at all. The item editor only displays stat 17: item_maxdamage_percent. Modifying this value will change the X% Enhanced Damage text to "Adds Y-X damage", with Y being the value you just set.
So increasing 20% enhanced damage to 30% will change the stat to "Adds 30-20 damage". This is invalid so the change is reverted by the game.
Adding item_maxdamage_percent to an item instead of changing a preexisting one will read:
"Adds Y-undefined damage."

Adding item_mindamage_percent as well to modify the other value will instead read:
"Adds Y-undefined damage.
Enhanced minimum damage."

**Comment by enders-blade** [comment]
I just modified a Superior weapon, using the editor I changed it to 15%.  Loaded it up ingame, and instead of 15% enhanced damage, I have 15% enhanced max damage.  Can confirm it is bugged.
