### ISSUE TITLE
Inventory error

### ISSUE THREAD

**Issue by jackg4** [dschu012/d2s-editor#25]
In the inventory, I keep a Book of Portals in the lower right-hand corner. When I use your amazing ds2-editor, the Book becomes useless. Luckily I haven't gotten stranded without an extra portal, but I have to remember to replace the Book when I use the editor. Thanks for your work on this editor!

**Comment by enders-blade** [comment]
Heh...I just posted this issue as well.  Changes the Tome of Town Portal to Tome of Identify, but it isn't useable.

**Comment by dschu012** [comment]
Duplicate #3
