### ISSUE TITLE
Tome of Town Portal being replaced by Tome of Identify

### ISSUE THREAD

**Issue by pires11d** [dschu012/d2s-editor#3]
It's just a minor bug I found, nothing serious at all... so anyway, here's what's happening: 

> I always carry two tomes of each kind in my inventory, and after editing my saves with the d2s-editor, I realized that both of them contained Identify "scrolls" inside (even though the name of both tomes was different...), showing a total of 40 identify scrolls to use, and no town portal on the spell menu. 
It happens everytime I edit ANY save with d2s-editor.

I really loved your app though, seriously. I was looking for something like that months ago, and couldn't find it!!! 
Guess I never looked in the right place haha :)
Peace out and keep up the good work!

**Comment by DNA64** [comment]
Confirming this is an issue for me as well.
