### ISSUE TITLE
Is there a way to play pandemonium event with this?

### ISSUE THREAD

**Issue by seriousgigi** [dschu012/d2s-editor#52]
sorry if asking this in here is wrong.

**Comment by BourbonCrow** [comment]
Yes you can just add 3 of each key.. to your inventory and kill the bosses  or skip that part completly and just add in the parts you get from doing the keys..
here you have all you need including their value so you can easly import them

1 of each key in cube.. open all 3 portals in same game
3x Key of Destruction (Sk0QAIAAZQAEArc2A4L8EpSBr+A/)
3x Key of Terror (Sk0QAIAAZQAGArcWAwKxk0YMqeA/)
3x Key of Hate (Sk0QAIAAZQAEArcmAwLI3VgNqOA/)
in cube this will get you into uber tristram directly...
1x Mephisto's Brain (Sk0QIKAAZABA0iYmBwI=)
1x Baal's Eye (Sk0QIKAAZAAgIlaWBwI=)
1x Diablo's Horn (Sk0QIKAAZAAAQobmBgI=)
