### ISSUE TITLE
Changing "item_maxdamage_percent" on weapon does not have desired effect

### ISSUE THREAD

**Issue by ddolsen** [dschu012/d2s-editor#56]
Changing the **item_maxdamage_percent** value on a weapon changes the attribute from **###% Enhanced Damage** to **Adds ###-### Damage**. I've only confirmed this behavior with a couple of polearm runewords (**Insight** and **Infinity**).

**Comment by BourbonCrow** [comment]
if you want "Enhanced Damage"
[](https://github.com/dschu012/d2s-editor/issues/87) check this post thats how i do it @ddolsen
