### ISSUE TITLE
Changing Ethereal status of equipped items changed tome of town portal into a tome of identify

### ISSUE THREAD

**Issue by hansrun** [dschu012/d2s-editor#57]
I used the tool to change an ethereal Skin of the Vipermagi into a non-eth. I also increased the resistances from 21 to 35 each. When I went in game my Tome of Town Portal still appeared as a normal Tome of Town Portal but acted as a Tome of Identify.
![tome skill menu](https://user-images.githubusercontent.com/93899576/140688586-8d91bdec-5fc9-4e7e-9410-9f62ff8c4920.png)
![tome of identify or tp](https://user-images.githubusercontent.com/93899576/140688641-721ada21-02b7-484d-ae44-962da80676dd.png)

**Comment by CyborgTrooper** [comment]
Same happened to me changing a couple of skill points with the tool


Here is the screenshot
![image](https://user-images.githubusercontent.com/6986687/140947827-1ef7ea30-af0f-4e2f-8c69-58347744c7e6.png)

**Comment by dschu012** [comment]
duplicate #3
