### ISSUE TITLE
DR2 SharedStash d2i support

### ISSUE THREAD

**Issue by stanislav-turovskiy** [dschu012/d2s-editor#6]
is implementation planned?

**Comment by dschu012** [comment]
currently no. the library supports reading those files, would just need to write a ui around it.

**Comment by stanislav-turovskiy** [comment]
are you planning to implement this in ui? it would be amazing

**Comment by dschu012** [comment]
eventually. but i've been to busy with other stuff to be able to spend time on this project. if you or someone else feels like tackling it, feel free.

**Comment by stanislav-turovskiy** [comment]
I ran all library tests using this file(SharedStash_SoftCore.d2i), all crashed with data inconsistency errors

**Comment by stanislav-turovskiy** [comment]
> currently no. the library supports reading those files, would just need to write a ui around it.
I ran all library tests using this file(SharedStash_SoftCore.d2i), all crashed with data inconsistency errors

**Comment by stanislav-turovskiy** [comment]
#72

**Comment by stanislav7777777** [comment]
#98
