### ISSUE TITLE
Constants generation

### ISSUE THREAD

**Issue by LeGrosWinnie** [dschu012/d2s-editor#83]
Hello,
I am trying to create my own version but when I go to constants.html and Run I don't get the same kind f result as the original file.
Are we supposed to replace the whole contant of the file "constants.bundle.min.js" ???
Original is like :
var constants=function(e){var i={};function

Mine is like :
window.constants = {"constants": {"classes":[{"n":"Amazon","c":"ama","ts":[null,null,null],"s":{"lpl":8,"mpl":6,"spl":4,"lpv":12,"spv":4,"mpe":6}},{"n":"Sorceress","c":"sor","ts":[null,null,null],"s":{"lpl":4,"mpl":8,"sp

In mine I have a lot of "null" (you can already see that just above) and "{}" :
"rare_names":[null,{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]

Same for magic_prefixes etc.

Anyone has a full guide of which files I need to extract from original storage ?

**Comment by LeGrosWinnie** [comment]
My goal is to try to create an editor that works for any mods with replacing unknow items, etc., with default item (like UdieToo did on its time, and it worked fine with a lot of mods).

**Comment by dschu012** [comment]
You would need to make something offline then and extracting them when running your tool. The txt files you need to extract from the casc are 
```
        "data/local/LNG/ENG/string.txt",
        "data/local/LNG/ENG/patchstring.txt",
        "data/local/LNG/ENG/expansionstring.txt",
        "data/global/excel/CharStats.txt",
        "data/global/excel/PlayerClass.txt",
        "data/global/excel/SkillDesc.txt",
        "data/global/excel/Skills.txt",
        "data/global/excel/RareSuffix.txt",
        "data/global/excel/RarePrefix.txt",
        "data/global/excel/MagicPrefix.txt",
        "data/global/excel/MagicSuffix.txt",
        "data/global/excel/Properties.txt",
        "data/global/excel/ItemStatCost.txt",
        "data/global/excel/Runes.txt",
        "data/global/excel/SetItems.txt",
        "data/global/excel/UniqueItems.txt",
        "data/global/excel/ItemTypes.txt",
        "data/global/excel/Armor.txt",
        "data/global/excel/Weapons.txt",
        "data/global/excel/Misc.txt",
        "data/global/excel/Gems.txt",
```

**Comment by LeGrosWinnie** [comment]
I tried to convert tbl to txt with the only tool I found but it does not change anything.
Example of what I get from the conversion :
ktr,	,	"Katar"
wrb,	,	"Wrist Blade"
ces,	,	"Cestus"
clw,	,	"Claws"
btl,	,	"Blade Talons"
skr,	,	"Scissors Katar"

![image](https://user-images.githubusercontent.com/39271928/152121016-57d3b17d-4945-4268-b6c3-201cee8cb80a.png)

**Comment by BourbonCrow** [comment]
> Nice it works (without changing the the constants file for now).
> 
> Still, why is the format not the same as original file when I generate it ? [constants.bundle.min.txt](https://github.com/dschu012/d2s-editor/files/7984867/constants.bundle.min.txt) [constants.bundle.min generated from original game.txt](https://github.com/dschu012/d2s-editor/files/7984868/constants.bundle.min.generated.from.original.game.txt)

i got same issue did you mange to figure it out .. if so how? x,x

**Comment by LeGrosWinnie** [comment]
> > Nice it works (without changing the the constants file for now).
> > Still, why is the format not the same as original file when I generate it ? [constants.bundle.min.txt](https://github.com/dschu012/d2s-editor/files/7984867/constants.bundle.min.txt) [constants.bundle.min generated from original game.txt](https://github.com/dschu012/d2s-editor/files/7984868/constants.bundle.min.generated.from.original.game.txt)
> 
> i got same issue did you mange to figure it out .. if so how? x,x

I just does what [dschu012](https://github.com/dschu012) said, extract all fils from mpq and put them at the same place as "css", "js", etc. so in at the root of the project.

For now I stoped working on it by the way as it is not my primary language.

**Comment by BourbonCrow** [comment]
```
        "data/local/LNG/ENG/string.txt",
        "data/local/LNG/ENG/patchstring.txt",
        "data/local/LNG/ENG/expansionstring.txt",
```
these coems as .tbl files not txt and i also tried converting them to txt  using AFJ tbl Edit 1.12u no matter how i do it the file dont generate correctly.. am i dented or what? o.o cause i got all the files mentioned in the correct folders  as listed above

**Comment by spg-stany** [comment]
#188
