### ISSUE TITLE
Sockets and also Armor

### ISSUE THREAD

**Issue by AmishApplesauce** [dschu012/d2s-editor#86]
I don't see any base items for armor.  Maybe I missed it, but I couldn't find it.  Also giving items the maximum number of sockets seems to be difficult.  Normal phase blade will start out at 3 (because it's item level 1 by default, but if you change the item level to 99 then the maximum sockets is 5 not 6

**Comment by Clintie-The-GIT** [comment]
agreed with OP. I cant create base weapons with more than 3 sockets :(

**Comment by ryancrunchi** [comment]
Same with war staff
item level 24
max sockets 6
when you save it only have 5 sockets

**Comment by spg-stany** [comment]
#101
