### ISSUE TITLE
Can't load a d2r file any more after patch 2.4

### ISSUE THREAD

**Issue by jackg4** [dschu012/d2s-editor#89]
I've loaded this d2r file before but after d2r patch 2.4, I can no longer load it. I tried an older save file and it loaded fine. I'm wondering if something has changed in save files after patch 2.4. I was able to create a new char without a problem just as a test.

**Comment by 717044** [comment]
Same. New D2R can't open save files from editor. Editor is broken till fix.

**Comment by hansrun** [comment]
Same. I broke an important character save file. When I replace it with my backup that hasn't been edited using the editor it still doesn't work. not sure if that's helpful info, but thought I'd mention it.

**Comment by Bogdanov89** [comment]
Gonna post here as well in case my thread isnt visible:
I found a solution to my problem, the editor will not fill the Name of a character that you load (it will be blank).
If i type the name as my character is named and copy/overwrite the saved file it will work normally.
So in my case the only issue is that the editor when opening existing characters does not fill the char name (leaves it blank) and that breaks the d2r loading.

**Comment by 717044** [comment]
This! Solved the problem.

**Comment by hansrun** [comment]
That worked! thank you!

**Comment by jackg4** [comment]
I'm using the online editor and don't see how the solution works. I'm dragging the char file .d2s to my desktop to work on it there. Renaming the file there doesn't help. A video of the solution is too much to ask, I know, but detailed steps for me might help if someone doesn't mind taking the time. Another char file works after the 2.4 patch so I don't have a clue why this char file doesn't work.

**Comment by Bogdanov89** [comment]
in the online editor (not the file name itself) the field called Name (under the tab Stats) must not be blank.

![image](https://user-images.githubusercontent.com/55892027/163868307-18be1669-1038-4f8a-b933-3b63299eda2e.png)

**Comment by jackg4** [comment]
Thanks for that picture, Boganov89. That explains what you were talking about, but my problem seems to be different. When I try to load a char file, absolutely nothing loads; no stats, name, nothing. The editor just ignores the file. Two of my char files act the same way, nothing. But another char saved last night was able to open in the editor. So, I'm still at a loss to explain.

**Comment by jackg4** [comment]
I found another char editor called D2Editor. I tried opening the problem char files in that and got an error: "Corrupt Diablo II character file detected. Invalid item inventory." So I took all of my equipment and inventory items off but still got the same message.

**Comment by jackg4** [comment]
I pinned the problem down on one of my characters. The editor didn't like a belt I had modified in Hero Editor; possibly the All Resistances 75%, not positive. Odd that the game d2r accepted the belt but the editor did not. I feel like I should be able to pin down the problem with the other 2 char files. Thanks to everyone that tried to help. And thanks for the editor.
